version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_USER: dbuser
      DB_PASSWORD: admin123
      DB_NAME: mydb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
