name: Publish Docker Image to DockerHub

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        id: login-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build-docker-image
        id: build-image
        run: |
          docker build -f Dockerfile -t pramod858/php-web-app:latest

      - name: push-to-dockerhub
        id: push-image
        run: |
          docker push pramod858/php-web-app:latest
        
