name: ECR Manager

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: create or delete'
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - delete
      repository_name:
        description: 'ECR Repository Name'
        required: true
        type: string

jobs:
  ecr:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'  # Replace with your AWS region

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check if ECR repository exists
        id: check_ecr_exists
        run: |
          EXISTS=$(aws ecr describe-repositories --repository-names ${{ github.event.inputs.repository_name }} || echo "RepositoryNotFoundException")
          if [[ "$EXISTS" == *"RepositoryNotFoundException"* ]]; then
            echo "repo_exists=false" >> $GITHUB_ENV
          else
            echo "repo_exists=true" >> $GITHUB_ENV
          fi

      - name: Create ECR repository
        if: (github.event.inputs.action == 'create') && (env.repo_exists == 'false')
        run: |
          aws ecr create-repository --repository-name ${{ github.event.inputs.repository_name }}
          echo "ECR repository ${{ github.event.inputs.repository_name }} created successfully."

      - name: Report ECR repository already exists
        if: (github.event.inputs.action == 'create') && (env.repo_exists == 'true')
        run: echo "ECR repository ${{ github.event.inputs.repository_name }} already exists."

      - name: Delete ECR repository
        if: (github.event.inputs.action == 'delete') && (env.repo_exists == 'true')
        run: |
          aws ecr delete-repository --repository-name ${{ github.event.inputs.repository_name }} --force
          echo "ECR repository ${{ github.event.inputs.repository_name }} deleted successfully."

      - name: Report ECR repository does not exist
        if: (github.event.inputs.action == 'delete') && (env.repo_exists == 'false')
        run: echo "ECR repository ${{ github.event.inputs.repository_name }} does not exist."
